### ISSUE TITLE
Next due report issues

### ISSUE THREAD

**Issue by AngieWork** [satsumah/Kubick-SSS#10]
- Is there any way we can get the Hours fields to be rounded to the 10ths or 100ths
- It doesn't seem like the date fields are actually sorting.   Can you test i
[Next Due Report.pdf](https://github.com/satsumah/Kubick-SSS/files/7533154/Next.Due.Report.pdf)
t?
https://drive.google.com/file/d/1IaJzBtZQ3wy4cVcPPYfr2oDVD7UGuMcG/view?usp=sharing

**Comment by satsumah** [comment]
1. Use Next Due Formatted, union queries do not support formatting
2. Fields with dates AND doubles will not sort properly (treated as text.)
