### ISSUE TITLE
New Component has #Name? in ServLifeCycles

### ISSUE THREAD

**Issue by AngieWork** [satsumah/Kubick-SSS#2]
Error message says Control cant be edited: its bound to unknown field "ServLifeCycles'.   Was adding new compnonent for new assembly for new aircraft

**Comment by satsumah** [comment]
Could not reproduce -- will have to demonstrate at the next meeting.

**Comment by AngieWork** [comment]
Ok - do you have time to meet tonight?

*Angela Healy*

Kubick Aviation Services, Inc. / KAS Enterprises, LLC

Business Operations Manager

250 Riverhills Road

Kingsford, MI 49802

(906)779-5500

(906)779-5526 (fax)

**Comment by satsumah** [comment]
Could not reproduce.

**Comment by AngieWork** [comment]
I am going to be working on the status sheet project tonight.  Can you make
sure any changes you have are pushed by 6pm tonight?

Thanks.

*Angela Healy*

Kubick Aviation Services, Inc. / KAS Enterprises, LLC

Business Operations Manager

250 Riverhills Road

Kingsford, MI 49802

(906)779-5500

(906)779-5526 (fax)
